services:
  app:
    build: .
    ports:
      - "80:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-primosfincntrl}
    restart: always

